### ISSUE TITLE
object_recognition_kitchen with Kinetic on Ubuntu 16.04

### ISSUE THREAD

**Issue by byeongkyu** [wg-perception/tabletop#31] opened 2016-09-06 01:15 UTC
How can I use the object_recognition_kitchen with Kinetic on Ubuntu 16.04 and Asus Xtion?

I tried install the ORK using binary (sudo apt install ros-kinetic-object-recognition-*) succesfully.

But, it is not include tabletop and has error while running tod.

[Error message]

Mesh and object is founded on CouchDB. I am check it.

byeongkyu@byeongkyu-iMac:~$ rosrun object_recognition_core training -c `rospack find object_recognition_tod`/conf/training.ork
Training 1 objects.
computing object_id: 96562faf31b4165800bb3f68d5006aeb
byeongkyu@byeongkyu-iMac:~$ 
byeongkyu@byeongkyu-iMac:~$ rosrun object_recognition_core detection -c `rospack find object_recognition_tod`/conf/detection.ros.ork
[ INFO] [1472790930.085746566]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1472790930.458528179]: System already initialized. node_name: /object_recognition_server
[ INFO] [1472790930.863419206]: System already initialized. node_name: /object_recognition_server
[ INFO] [1472790930.871813965]: Subscribed to topic:/camera/depth/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1472790930.876186903]: Subscribed to topic:/camera/depth/image_raw [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1472790930.881230116]: Subscribed to topic:/camera/rgb/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1472790930.885333776]: Subscribed to topic:/camera/rgb/image_raw [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1472790931.620373761]: publishing to topic:/recognized_object_array
Loading models. This may take some time...
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/object_recognition_core/detection", line 24, in <module>
    run_plasm(args, plasm)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = pipeline1

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = Matcher

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] = Object Not Found : http://localhost:5984/object_recognition/占쏙옙e

[when] = While triggering param change callbacks

terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::lock_error >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)
And. I am tried also install using rosinstall. reference [http://wg-perception.github.io/object_recognition_core/install.html#install]

But, it is failed to running tabletop, tod.

[Error Message]

byeongkyu@byeongkyu-iMac:~$ rosrun object_recognition_core detection -c `rospack find object_recognition_tabletop`/conf/detection.object.ros.ork
[ INFO] [1472793255.037448839]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1472793255.416741080]: System already initialized. node_name: /object_recognition_server
[ INFO] [1472793255.777974609]: System already initialized. node_name: /object_recognition_server
[ INFO] [1472793255.792620349]: Subscribed to topic:/camera/depth_registered/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1472793255.796001824]: Subscribed to topic:/camera/rgb/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1472793255.799017281]: Subscribed to topic:/camera/depth_registered/image_raw [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1472793255.802311035]: Subscribed to topic:/camera/rgb/image_rect_color [queue_size: 1][tcp_nodelay: 0]
133 :: 0.5 , 1 , 0.995004 , /base_link , /head_mount_kinect_rgb_optical_frame
[ INFO] [1472793256.744593721]: publishing to topic:/tabletop/clusters
[ INFO] [1472793256.745550347]: publishing to topic:/table_array
Traceback (most recent call last):
  File "/home/byeongkyu/catkin_ws/src/ork/ork_core/apps/detection", line 24, in <module>
    run_plasm(args, plasm)
  File "/home/byeongkyu/catkin_ws/src/ork/ecto/python/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = pipeline2

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = <class 'object_recognition_tabletop.ecto_cells.tabletop_object.objectrecognizer'="">

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] = value type is 0 not 2

[when] = While triggering param change callbacks

terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::lock_error >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argumen

**Comment by drmateo** [comment] 2016-09-15 23:16
For me the same, I get the those exceptions. The only difference is that I'm using a Kinect v1 while I'm following the tutorial:
http://wg-perception.github.io/ork_tutorials/tutorial02/tutorial.html`

I just get it work this tutorial with the compile apt version in Ubuntu 14.04 and ROS Indigo

**Comment by corot** [comment] 2016-11-19 14:48
The same also for me when running object_recognition_tabletop. I think I found where the problem is, but only a very hackish solution, and I don't really understand what's wrong. See this issue https://github.com/wg-perception/object_recognition_core/issues/45

**Comment by hris2003** [comment] 2017-02-09 09:18
Fixed with the latest version of object_recognition_core. Closed.

**Closed as completed by hris2003** 2017-02-09 09:18 UTC
